[example] add example for recognizer with grammar
Bear-03/vosk-rs pull request #4
Opened 2022-07-26 21:13 UTC by kawaki-san

This provides a quick demo of the using `Recognizer::new_with_grammar` API

2022-07-26 22:03 UTC, Bear-03 requested changes
Thanks for the contribution!

2022-07-26 22:55 UTC, kawaki-san commented on vosk/examples/grammar.rs
> +        let stream = recognizer.accept_waveform(sample);
How about just `state` as per [mic example](https://github.com/Bear-03/vosk-rs/blob/1e7db5a1f09808b8003541830a4e44d986c154f4/vosk/examples/microphone.rs#L97) or alternatively, matching directly on `Recognizer::accept_waveform` for less verbosity

2022-07-26 23:07 UTC, Bear-03 commented on vosk/examples/grammar.rs
> +        let stream = recognizer.accept_waveform(sample);
Both options seem good, but matching directly would make the line too long, so I prefer `state`, which also makes things consistent. Thanks for pointing it out!

2022-07-26 23:14 UTC, kawaki-san commented on vosk/examples/grammar.rs
> +        let stream = recognizer.accept_waveform(sample);
Sorted!

2022-07-27 09:33 UTC, Bear-03 approved these changes
Looks good to me, thanks!

2022-07-27 09:34 UTC, merged